node {
 properties([
  pipelineTriggers([
   causeString: '$committer_name pushed tag $tag to $clone_url referencing $commit',
    
    token: 'abc123',
    
    printContributedVariables: true,
    printPostContent: true,
    
    regexpFilterText: '$ref',
    regexpFilterExpression: '^refs/tags/.*'
   
  ])
 ])

 stage("Prepare") {
  deleteDir()
  sh '''
  echo git clone $clone_url
  echo git checkout $commit
  sleep 1
  '''
 }

 stage("Build") {
  sh '''
  echo Validate that artifact version is $tag
  echo Or, set artifact version to $tag, without committing it or pushing!
  echo ./gradlew build
  sleep 2
  '''
 }

 stage("Upload") {
  sh '''
  echo Uploading...
  sleep 1
  '''
 }

}
